import { MainLayout } from '../../layout/MainLayout';

export const ProfilePage = () => {
    return (
        <MainLayout>
            <h1>Profile</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a sem ut mauris suscipit vulputate. Vestibulum magna nulla, vulputate eu enim non, suscipit consectetur sem. Sed vel tincidunt risus. Suspendisse rhoncus nisl id libero posuere, ac luctus ex maximus. Fusce mollis pretium elementum. Mauris pretium sem sed fringilla dictum. Nunc at lacinia nisi, at gravida ligula. Ut ultricies quis leo nec lacinia. Nulla facilisi. Duis sit amet neque nec augue pellentesque bibendum. Pellentesque ornare efficitur iaculis. Proin eu eros consequat, pretium ante ac, gravida purus. Aliquam ullamcorper magna orci, non pharetra urna viverra at. Fusce semper, sapien non dictum pretium, neque ligula auctor lacus, non egestas urna purus vitae lectus. Maecenas dui nisl, pharetra ac vulputate sit amet, rhoncus non sapien.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a sem ut mauris suscipit vulputate. Vestibulum magna nulla, vulputate eu enim non, suscipit consectetur sem. Sed vel tincidunt risus. Suspendisse rhoncus nisl id libero posuere, ac luctus ex maximus. Fusce mollis pretium elementum. Mauris pretium sem sed fringilla dictum. Nunc at lacinia nisi, at gravida ligula. Ut ultricies quis leo nec lacinia. Nulla facilisi. Duis sit amet neque nec augue pellentesque bibendum. Pellentesque ornare efficitur iaculis. Proin eu eros consequat, pretium ante ac, gravida purus. Aliquam ullamcorper magna orci, non pharetra urna viverra at. Fusce semper, sapien non dictum pretium, neque ligula auctor lacus, non egestas urna purus vitae lectus. Maecenas dui nisl, pharetra ac vulputate sit amet, rhoncus non sapien.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a sem ut mauris suscipit vulputate. Vestibulum magna nulla, vulputate eu enim non, suscipit consectetur sem. Sed vel tincidunt risus. Suspendisse rhoncus nisl id libero posuere, ac luctus ex maximus. Fusce mollis pretium elementum. Mauris pretium sem sed fringilla dictum. Nunc at lacinia nisi, at gravida ligula. Ut ultricies quis leo nec lacinia. Nulla facilisi. Duis sit amet neque nec augue pellentesque bibendum. Pellentesque ornare efficitur iaculis. Proin eu eros consequat, pretium ante ac, gravida purus. Aliquam ullamcorper magna orci, non pharetra urna viverra at. Fusce semper, sapien non dictum pretium, neque ligula auctor lacus, non egestas urna purus vitae lectus. Maecenas dui nisl, pharetra ac vulputate sit amet, rhoncus non sapien.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a sem ut mauris suscipit vulputate. Vestibulum magna nulla, vulputate eu enim non, suscipit consectetur sem. Sed vel tincidunt risus. Suspendisse rhoncus nisl id libero posuere, ac luctus ex maximus. Fusce mollis pretium elementum. Mauris pretium sem sed fringilla dictum. Nunc at lacinia nisi, at gravida ligula. Ut ultricies quis leo nec lacinia. Nulla facilisi. Duis sit amet neque nec augue pellentesque bibendum. Pellentesque ornare efficitur iaculis. Proin eu eros consequat, pretium ante ac, gravida purus. Aliquam ullamcorper magna orci, non pharetra urna viverra at. Fusce semper, sapien non dictum pretium, neque ligula auctor lacus, non egestas urna purus vitae lectus. Maecenas dui nisl, pharetra ac vulputate sit amet, rhoncus non sapien.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a sem ut mauris suscipit vulputate. Vestibulum magna nulla, vulputate eu enim non, suscipit consectetur sem. Sed vel tincidunt risus. Suspendisse rhoncus nisl id libero posuere, ac luctus ex maximus. Fusce mollis pretium elementum. Mauris pretium sem sed fringilla dictum. Nunc at lacinia nisi, at gravida ligula. Ut ultricies quis leo nec lacinia. Nulla facilisi. Duis sit amet neque nec augue pellentesque bibendum. Pellentesque ornare efficitur iaculis. Proin eu eros consequat, pretium ante ac, gravida purus. Aliquam ullamcorper magna orci, non pharetra urna viverra at. Fusce semper, sapien non dictum pretium, neque ligula auctor lacus, non egestas urna purus vitae lectus. Maecenas dui nisl, pharetra ac vulputate sit amet, rhoncus non sapien.</p>
        </MainLayout>
    )
}
